# Generated by Django 3.2.6 on 2021-08-28 14:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTranscations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amout', models.DecimalField(decimal_places=1, max_digits=20, verbose_name='Money/Amount in INR')),
                ('type_of_trans', models.CharField(blank=True, choices=[('debit', 'Income/Debit'), ('credit', 'Expence/Credit')], max_length=100, null=True)),
                ('cat_of_trans', models.CharField(blank=True, choices=[('family', 'Family'), ('friends', 'Friends'), ('food', (('healthy', 'Healthy'), ('outdoor', 'Outdoor'))), ('outings', 'Outings'), ('medical', 'Medical'), ('travel', 'Travel'), ('rent', (('house', 'House Rent'), ('pg', 'PG rent'), ('others', 'others'))), ('bills', (('electric Bill', 'Electric Bill'), ('phone_bill', 'Phone Bill'), ('water_bill', 'Water Bill'))), ('maintenance', (('bike', 'Bike'), ('home', 'Home'), ('personal_gromming', 'Personal Gromming'))), ('tax', 'Tax'), ('shopping', (('gadgets', 'Gadgets'), ('appliances', 'Appliances'), ('grocceries', 'Groceries'), ('cloths', 'Cloths'), ('jewellery', 'Jewellery'))), ('Repayment', (('loan', 'Loan'), ('emi', 'EMI'))), ('investment', 'Investment'), ('Purchase', (('bike', 'Bike'), ('car', 'Car'), ('cycle', 'Cycle'), ('other', 'Others'))), ('pets', 'Pets'), ('games', 'Games'), ('charity_works', 'Charity works'), ('gifts', 'Gifts'), ('income', 'Income')], max_length=200, null=True)),
                ('trans_date', models.DateField(default=datetime.datetime.now, verbose_name='Transaction Date')),
                ('trans_hour', models.IntegerField(default=datetime.datetime.now, null=True, verbose_name='Transaction Hour')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp of transaction entry')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Timestamp of transaction entry')),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank_transfer', 'Bank transfer'), ('vouchers', 'Vouchers'), ('cheque', 'Cheque'), ('others', 'Others'), ('cash_backs', 'Cash backs'), ('miscellaneous', 'Miscellaneous')], max_length=40, verbose_name='Payment Mode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
