# Generated by Django 3.2.6 on 2021-09-01 16:14

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BankTranscations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=1, max_digits=20, verbose_name='Money/Amount in INR')),
                ('type_of_trans', models.CharField(blank=True, choices=[('debit', 'Expense/Debit'), ('credit', 'Income/Credit')], max_length=100, null=True)),
                ('cat_of_trans', models.CharField(blank=True, choices=[('family', 'Family'), ('friends', 'Friends'), ('food', (('healthy', 'Healthy'), ('outdoor', 'Outdoor'))), ('outings', 'Outings'), ('medical', 'Medical'), ('travel', 'Travel'), ('rent', (('house', 'House Rent'), ('pg', 'PG rent'), ('others', 'others'))), ('bills', (('electric Bill', 'Electric Bill'), ('phone_bill', 'Phone Bill'), ('water_bill', 'Water Bill'))), ('maintenance', (('bike', 'Bike'), ('home', 'Home'), ('personal_gromming', 'Personal Gromming'))), ('tax', 'Tax'), ('shopping', (('gadgets', 'Gadgets'), ('appliances', 'Appliances'), ('grocceries', 'Groceries'), ('cloths', 'Cloths'), ('jewellery', 'Jewellery'))), ('Repayment', (('loan', 'Loan'), ('emi', 'EMI'))), ('investment', 'Investment'), ('Purchase', (('bike', 'Bike'), ('car', 'Car'), ('cycle', 'Cycle'), ('other', 'Others'))), ('pets', 'Pets'), ('games', 'Games'), ('charity_works', 'Charity works'), ('gifts', 'Gifts'), ('income', 'Income')], max_length=200, null=True)),
                ('trans_date', models.DateField(default='2021-09-01', null=True, verbose_name='Transaction Date')),
                ('trans_hour', models.IntegerField(default='21', null=True, verbose_name='Transaction Hour')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp of transaction entry')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Timestamp of transaction entry')),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank_transfer', 'Bank transfer'), ('vouchers', 'Vouchers'), ('cheque', 'Cheque'), ('others', 'Others'), ('cash_backs', 'Cash backs'), ('miscellaneous', 'Miscellaneous')], max_length=40, verbose_name='Payment Mode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
