# Generated by Django 3.2.6 on 2021-09-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktranscations',
            name='trans_date',
            field=models.DateField(default='2021-09-08', null=True, verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='banktranscations',
            name='trans_hour',
            field=models.IntegerField(default='19', null=True, verbose_name='Transaction Hour'),
        ),
    ]
