# Generated by Django 3.2.6 on 2021-09-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0002_auto_20210908_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktranscations',
            name='trans_hour',
            field=models.IntegerField(default='20', null=True, verbose_name='Transaction Hour'),
        ),
    ]
