# Generated by Django 3.2.6 on 2021-09-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0002_auto_20210906_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktranscations',
            name='trans_hour',
            field=models.IntegerField(default='17', null=True, verbose_name='Transaction Hour'),
        ),
    ]
