# Generated by Django 3.2.6 on 2021-09-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0003_alter_banktranscations_trans_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktranscations',
            name='trans_hour',
            field=models.IntegerField(default='21', null=True, verbose_name='Transaction Hour'),
        ),
    ]
