# Generated by Django 3.2.6 on 2021-09-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0003_auto_20210901_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktranscations',
            name='trans_date',
            field=models.DateField(default='2021-09-05', null=True, verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='banktranscations',
            name='trans_hour',
            field=models.IntegerField(default='10', null=True, verbose_name='Transaction Hour'),
        ),
    ]
