# Generated by Django 3.2.6 on 2021-09-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0005_auto_20210905_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktranscations',
            name='trans_hour',
            field=models.IntegerField(default='15', null=True, verbose_name='Transaction Hour'),
        ),
    ]
